on: [push]
name: Deploy Hugo to Firebase
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        firebase-token: 1//09RdMsmD1excECgYIARAAGAkSNwF-L9IrlEm9Ie3Hnp5fl1WqWj__8lKpn7z51AlVhVOHgXbYbYb6eCLhd0wsTCmjzaSi1RukAGw
